# Azure DevOps Pipeline for .NET app with azd deployment
# Save as azure-pipelines.yml in the repo root

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_ENV_NAME: 'dev'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore src/Web/Web.csproj
    dotnet build src/Web/Web.csproj --configuration Release
    dotnet publish src/Web/Web.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Build and Publish .NET Web App'

- task: AzureCLI@2
  inputs:
    azureSubscription: '<your-azure-service-connection>'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      curl -fsSL https://aka.ms/install-azd.sh | bash
      azd auth login --service-principal -c $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) -t $(AZURE_TENANT_ID)
      azd up --no-prompt --environment $(AZURE_ENV_NAME)
    failOnStandardError: true
  displayName: 'Deploy with azd'

# Note: Replace <your-azure-service-connection> and set secrets for AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID in your pipeline variables.